export const workflows = [
  {
    id: 'wf-001',
    name: 'Deep Research and Summary',
    description: 'A multi-step workflow to conduct deep research on a topic, synthesize the findings, and provide a high-quality summary.',
    category: 'Research & Analysis',
    promptIds: [6, 7, 8, 9],
  },
  {
    id: 'wf-002',
    name: 'Internal Knowledge Research',
    description: 'A workflow to generate a detailed summary of a topic using internal knowledge.',
    category: 'Research & Analysis',
    promptIds: [10, 7, 8, 9],
  },
  {
    id: 'wf-003',
    name: 'Creative Story Writing',
    description: 'A workflow to help brainstorm, outline, and write a creative story with character development and plot structure.',
    category: 'Creative Writing',
    promptIds: [11, 12, 13, 14],
  },
  {
    id: 'wf-004',
    name: 'Code Review and Optimization',
    description: 'A systematic approach to reviewing code, identifying issues, and suggesting improvements for performance and maintainability.',
    category: 'Development',
    promptIds: [15, 16, 17],
  },
  {
    id: 'wf-005',
    name: 'Problem Solving Framework',
    description: 'A structured approach to analyzing problems, generating solutions, and implementing fixes.',
    category: 'Problem Solving',
    promptIds: [18, 19, 20],
  },
  {
    id: 'wf-006',
    name: 'Learning and Understanding',
    description: 'A workflow to break down complex topics, explain concepts clearly, and ensure comprehension.',
    category: 'Education',
    promptIds: [21, 22, 23],
  },
  {
    id: 'wf-007',
    name: 'Project Planning',
    description: 'A comprehensive workflow to plan projects, create timelines, and organize tasks effectively.',
    category: 'Planning',
    promptIds: [24, 25, 26],
  },
];